### ISSUE TITLE
Feature request: skip step if argument is provided

### ISSUE THREAD

**Issue by Kehet** [shomisha/laravel-console-wizard#1]
I very often use trait like this in my projects 

```php
<?php

namespace App\Console\Traits;

trait ArgumentOrAsk
{

    public function argumentOrAsk($name, $question = null, $default = null)
    {
        $argument = $this->argument($name);

        if (!empty($argument)) {
            return $argument;
        }

        return $this->ask($question ?? $name, $default);
    }
}
```

and I think it would be great if step could read value from arguments and maybe even ask that value again if validation rules fail

**Comment by shomisha** [comment]
@Kehet Hi.

Thanks for the request. I like the idea, however I don't think that should be default behavior of the Wizards. 

I'll implement something like this, however I'll make it configurable, Wizards will probably have some switch in the form of a protected property called `protected bool $overridableByArguments` that will default to `false`, and you'll be able enable this feature by overriding that property to `true`.

**Comment by shomisha** [comment]
Hello again @Kehet 

I implemented the features you requested, however with some changes to the flow you proposed.

It does not make sense to me to couple parsing step answers from the command line and automatically repeating steps upon validation failure, however I liked both of those ideas separately. 

So what I did was introduce inheriting data from the command line as one feature, and automatically repeating failed steps as a new validation strategy.

Please take a look at these two parts of the documentation in order to learn how you can achieve what you requested in your comment:

1. [Parsing step answers from the command line](https://github.com/shomisha/laravel-console-wizard/wiki/Using-the-wizard#inheriting-input-from-command-arguments-and-options)
2. [Automatically repeating steps upon invalid answers](https://github.com/shomisha/laravel-console-wizard/wiki/Validation#2-repeating-steps-with-invalid-answers)
