### ISSUE TITLE
why not support 7.3 with polyfill?

### ISSUE THREAD

**Issue by lorvent** [shomisha/laravel-console-wizard#2]
Still many people use php 7.3 as that is the laravel's required version,
so it would be better if you can support php7.3 using polyfill

thanks.

**Comment by shomisha** [comment]
Hi, thanks for the message.

Laravel Console Wizard requires PHP 7.4 only since version 1.7, you can use earlier versions with PHP 7.3

There currently are no big changes between 1.7 and 1.6, the only reason I introduced a minor version is due to the introduction of typed properties within the package's source.

Although PHP 7.3 still is Laravel's required version, it's been around for some time now and I think it should be adopted.

Having said all that, I don't find it particularly worth to invest my time into supporting PHP 7.3 again.

Hope this is okay with you, and keeping my fingers crossed you'll upgrade to PHP 7.4 and use the package 🤞
